# kubernetes/apps/app1/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        # The image name here should have been app:v1 or alike...here its just v1
        image: davidmartinprivate/mytestingrepository:v1
        ports:
        - containerPort: 8080